name: Check JavaScript for conformance with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Configure npm caching
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
        restore-keys: |
          ${{ runner.os }}-npm-
<<<<<<< HEAD
<<<<<<< HEAD
    - run: npm ci
=======
>>>>>>> eb05f7e (push prettier action)
=======
    - run: npm ci
>>>>>>> 832b782 (add npm ci to prettier.yml)
    - name: Run prettier
      run: npm run pretty